name: develop

on:
  schedule:
    - cron: "0 19 * * *"

jobs:
  develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          path: 'develop'

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          repository: 'jaywcjlove/reference'
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Checkout record 
        uses: actions/checkout@v4
        with:
          ref: 'record'
          path: 'record'
        continue-on-error: true

      - name: Read last-commit
        run: |
          cd ./develop
          develop_last_commit=$(git rev-parse HEAD)
          cd ..

          cd ./gh-pages
          gh_pages_last_commit=$(git rev-parse HEAD)
          cd ..

          cd ./record
          if [ ! -f develop.txt ]; then
            echo "null" > develop.txt
          fi
          if [ ! -f gh-pages.txt ]; then
            echo "null" > gh-pages.txt
          fi
          develop_record_commit=$(cat develop.txt)
          gh_pages_record_commit=$(cat gh-pages.txt)
          echo "develop_record_commit: $develop_record_commit"
          echo "develop_last_commit: $develop_last_commit"
          echo "gh_pages_record_commit: $gh_pages_record_commit"
          echo "gh_pages_last_commit: $gh_pages_last_commit"
          if [ "$develop_record_commit" != "$develop_last_commit" ]; then
            echo "develop_update=true" >> $GITHUB_ENV
            echo "$develop_last_commit" > develop.txt
          else
            echo "develop_update=false" >> $GITHUB_ENV
          fi
          if [ "$gh_pages_record_commit" != "$gh_pages_last_commit" ]; then
            echo "gh_pages_update=true" >> $GITHUB_ENV
            echo "$gh_pages_last_commit" > gh-pages.txt
          else
            echo "gh_pages_update=false" >> $GITHUB_ENV
          fi

      - name: Config ssh
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SERVER_PORT: ${{ secrets.SERVER_PORT}}

      - name: develop update
        if: env.develop_update == 'true'
        run: |
          echo "develop_update"
          cd ./develop
          rm -rf .git
          scp -r -P $SERVER_PORT ./* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SERVER_PORT: ${{ secrets.SERVER_PORT}}

      - name: gh-pages update
        if: env.gh_pages_update == 'true'
        run: |
          echo "gh_pages_update"
          cd ./gh-pages
          rm -rf .git
          scp -r -P $SERVER_PORT ./* $SERVER_USER@$SERVER_HOST:$REFERENCE_PATH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SERVER_PORT: ${{ secrets.SERVER_PORT}}

      - name: record update
        if: env.develop_update == 'true' || env.gh_pages_update == 'true'
        run: |
          echo "any update"
          cd ./record
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "$(date)"
          git push origin HEAD:record

